### ISSUE TITLE
Activity post / bp-attachments bridge

### ISSUE THREAD

**Issue by boonebgorges** [mrpritchett/buddydrive#68]
It would be <3 <3 <3 if a user could add a BuddyDrive file as part of the activity post process, especially using the bp-attachments UX you built. I imagine it'd be fairly easy for me to take the front-end and upload-handling parts of bp-attachments and pipe it together with BuddyDrive's storage mechanisms for a custom site, but I think it could be a cool feature for the plugin itself.

**Comment by imath** [comment]
I totally agree!

1) you can already, since 1.3, use BuddyDrive to add public files into the activity stream.
see: https://github.com/imath/buddydrive/wiki/The-BuddyDrive-Editor
I agree the thickbox window is not great.

2) It's actually on my todos :)
My plan was to first completely revamp the BuddyDrive UI, which is about to be done in 2.0.0 (should be released before the end of the week). But you can already test its beta on the BuddyPress test drive we used for the Avatar/cover image testing.
Then work on a new activity post form on the next-template-packs (or legacy)
Then extend it.

About the bp-attachments UX i've built, the main trouble of it is it completely replaces the activity post form, so i'm not sure it's something i could do with BuddyDrive ;)
